version: '3'

services:
  browser-headless:
    image: akkuman/firefox-cdp:latest
    restart: always
    ports:
      - "9222:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
